### ISSUE TITLE
Large snapshots getting stuck

### ISSUE THREAD

**Issue by Lt-Salty** [imagegenius/docker-kopia#1]
I'm trying to bacup my main video share. it's about 5TB.  I'm backing up a powerful server, 13700k, to a mini pc (zimaboard 832 with a single 20TB drive and PCIE card for nvme cache)at first it moves data fine, saturating 1 Gb LAN. but once it moves a TB or so it just starts to stop for long periods of time. Nothing seems to be moving, CPU usage is low, no apparent reads or writes on the disk.   I just have no idea what its doing.
Yesterday I was at 47% complete and today when I checked it was only at 50.5% and it hasn't moved any data for the last 2 hours. here is what the logs for the snapshot say right now for the last few hours
`
06:59:56.152 keeping 2023-10-03 04:25:11.547853175 -0400 EDT retention: [incomplete] pins: []
--
06:59:56.152 keeping 2023-10-03 05:25:08.292752798 -0400 EDT retention: [incomplete] pins: []
06:59:56.152 keeping 2023-10-03 05:50:04.345345163 -0400 EDT retention: [incomplete] pins: []
06:59:56.152 keeping 2023-10-03 06:59:56.097123511 -0400 EDT retention: [incomplete] pins: []
08:00:18.881 checkpointed root kcfe4d63986fd4e011ef73d39af93c100
08:00:18.883 deleting 1696317756459797613
08:00:18.883 keeping 2023-10-03 04:25:11.547853175 -0400 EDT retention: [incomplete] pins: []
08:00:18.883 keeping 2023-10-03 05:25:08.292752798 -0400 EDT retention: [incomplete] pins: []
08:00:18.883 keeping 2023-10-03 05:50:04.345345163 -0400 EDT retention: [incomplete] pins: []
08:00:18.883 keeping 2023-10-03 06:59:56.097123511 -0400 EDT retention: [incomplete] pins: []
08:00:18.883 keeping 2023-10-03 08:00:18.881369953 -0400 EDT retention: [incomplete] pins: []
08:59:37.208 checkpointed root k4990422056c9eabb5b5d8a4ca05ae0ae
08:59:37.237 deleting 1696321511547853175
08:59:37.238 keeping 2023-10-03 05:25:08.292752798 -0400 EDT retention: [incomplete] pins: []
08:59:37.239 keeping 2023-10-03 05:50:04.345345163 -0400 EDT retention: [incomplete] pins: []
08:59:37.239 keeping 2023-10-03 06:59:56.097123511 -0400 EDT retention: [incomplete] pins: []
08:59:37.239 keeping 2023-10-03 08:00:18.881369953 -0400 EDT retention: [incomplete] pins: []
08:59:37.240 keeping 2023-10-03 08:59:37.210700866 -0400 EDT retention: [incomplete] pins: []
09:57:55.236 checkpointed root k07041414f1669c6ab46e4c51577e6007
09:57:55.248 deleting 1696325108292752798
09:57:55.249 deleting 1696326604345345163
09:57:55.249 keeping 2023-10-03 06:59:56.097123511 -0400 EDT retention: [incomplete] pins: []
09:57:55.250 keeping 2023-10-03 08:00:18.881369953 -0400 EDT retention: [incomplete] pins: []
09:57:55.250 keeping 2023-10-03 08:59:37.210700866 -0400 EDT retention: [incomplete] pins: []
09:57:55.253 keeping 2023-10-03 09:57:55.238038438 -0400 EDT retention: [incomplete] pins: []`

Any idea what its trying to do and what I can do to speed it up? is a single 5TB snapshot just too big?

**Comment by hydazz** [comment]
seems like an kopia issue? https://github.com/kopia/kopia
