### ISSUE TITLE
Cannot create new reporitory

### ISSUE THREAD

**Issue by tulipo** [imagegenius/docker-kopia#4]
I'm trying to make kopia work but it seems more difficult than expected.

I create a rclone config for sftp server through ssh and i can also list file on the remote.

When i try to setup kopia on the UI i get this error creating a repository password:

Connect Error: INTERNAL: internal server error: connect error: unable to write blobcfg blob: PutBlob() failed for "kopia.blobcfg": unable to complete PutBlob(kopia.blobcfg) despite 10 retries: Write kopia.blobcfg.f-8976335210907794354: 405

I'm using kopia on Unraid. I also tried to use the docker on privileged mode but it seems not work the same.

**Comment by hydazz** [comment]
Have you tried just using the sftp build in to kopia?
https://kopia.io/docs/reference/command-line/common/repository-create-sftp/

**Comment by tulipo** [comment]
Yes i already tried too. After further investigation it seems to be a permission problem from the other side.
